# Generated by Django 4.2.26 on 2025-11-19 01:59

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('duration_days', models.PositiveIntegerField(help_text='Package duration in days')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in THB', max_digits=10)),
                ('features', models.JSONField(blank=True, default=dict, help_text='Package features as JSON')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Subscription Package',
                'verbose_name_plural': 'Subscription Packages',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='UserTradeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('account_name', models.CharField(max_length=200)),
                ('mt5_account_id', models.CharField(help_text='MT5 Account Number', max_length=100)),
                ('broker_name', models.CharField(max_length=100)),
                ('mt5_server', models.CharField(max_length=100)),
                ('subscription_start', models.DateTimeField(db_index=True)),
                ('subscription_expiry', models.DateTimeField(db_index=True)),
                ('subscription_status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], db_index=True, default='PENDING', max_length=20)),
                ('bot_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DOWN', 'Server Down')], db_index=True, default='PAUSED', max_length=20)),
                ('trade_config', models.JSONField(blank=True, default=dict, help_text='Trading configuration: lot_size, timeframes (M5, M15), notification_settings')),
                ('last_sync_datetime', models.DateTimeField(blank=True, null=True)),
                ('current_balance', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Current account balance', max_digits=19)),
                ('subscription_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscribed_accounts', to='trading.subscriptionpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Trade Account',
                'verbose_name_plural': 'User Trade Accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('line_uuid', models.CharField(db_index=True, max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TradeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('mt5_order_id', models.BigIntegerField(db_index=True, help_text='MT5 Order Ticket Number')),
                ('symbol', models.CharField(db_index=True, help_text='Trading symbol (e.g., EURUSD)', max_length=20)),
                ('position_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], default='BUY', max_length=10)),
                ('position_status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('PENDING', 'Pending')], db_index=True, default='OPEN', max_length=20)),
                ('opened_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('take_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('profit_loss', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Profit/Loss amount', max_digits=19)),
                ('commission', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('swap_fee', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=19)),
                ('account_balance_at_close', models.DecimalField(blank=True, decimal_places=4, help_text='Account balance when position was closed', max_digits=19, null=True)),
                ('trade_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='trading.usertradeaccount')),
            ],
            options={
                'verbose_name': 'Trade Transaction',
                'verbose_name_plural': 'Trade Transactions',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Amount in THB', max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(blank=True, help_text='e.g., PromptPay, Bank Transfer', max_length=50)),
                ('transaction_reference', models.CharField(blank=True, help_text='Payment reference or transaction ID', max_length=200)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_slip', models.ImageField(blank=True, help_text='Upload payment slip image', null=True, upload_to='payment_slips/%Y/%m/')),
                ('admin_notes', models.TextField(blank=True, help_text='Admin verification notes')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('subscription_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='trading.subscriptionpackage')),
                ('trade_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trading.usertradeaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Payment',
                'verbose_name_plural': 'Subscription Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='usertradeaccount',
            constraint=models.UniqueConstraint(fields=('user', 'mt5_account_id'), name='unique_user_mt5_account'),
        ),
        migrations.AddIndex(
            model_name='tradetransaction',
            index=models.Index(fields=['trade_account', '-opened_at'], name='trading_tra_trade_a_7e6e78_idx'),
        ),
        migrations.AddIndex(
            model_name='tradetransaction',
            index=models.Index(fields=['symbol', 'opened_at'], name='trading_tra_symbol_e0a1cc_idx'),
        ),
        migrations.AddIndex(
            model_name='tradetransaction',
            index=models.Index(fields=['position_status', '-opened_at'], name='trading_tra_positio_02b9be_idx'),
        ),
    ]
