# Generated by Django 4.2.26 on 2025-11-19 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAPIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('key', models.CharField(db_index=True, help_text='Master API key for bot authentication', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Descriptive name for this API key', max_length=100)),
                ('last_used', models.DateTimeField(blank=True, help_text='Last time this API key was used', null=True)),
            ],
            options={
                'verbose_name': 'Bot API Key',
                'verbose_name_plural': 'Bot API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
