# Generated by Django 4.2.26 on 2025-11-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_botapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='line_display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='line_picture_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
