# Generated by Django 4.2.26 on 2025-11-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_userprofile_line_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='line_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
