# Generated by Django 4.2.26 on 2025-11-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_userprofile_line_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradetransaction',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('TP', 'TP'), ('SL', 'SL'), ('MARGIN_CALL', 'Margin Call')], help_text='Reason for closing the position', max_length=20, null=True),
        ),
    ]
