# Generated by Django 4.2.26 on 2025-11-26 10:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_tradetransaction_close_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradeaccount',
            name='bot_activated_at',
            field=models.DateTimeField(blank=True, help_text='When the bot was activated for this account', null=True),
        ),
        migrations.CreateModel(
            name='BotStrategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(help_text='Bot strategy name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the bot strategy')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BETA', 'Beta')], db_index=True, default='INACTIVE', help_text='Bot availability status', max_length=20)),
                ('version', models.CharField(default='1.0.0', help_text='Bot version', max_length=50)),
                ('strategy_type', models.CharField(blank=True, help_text='Strategy type (e.g., Trend Following, Mean Reversion, Scalping)', max_length=100)),
                ('allowed_symbols', models.JSONField(blank=True, default=list, help_text="List of trading symbols this bot supports (e.g., ['XAUUSD', 'EURUSD'])")),
                ('optimization_config', models.JSONField(blank=True, default=dict, help_text='Optimization settings: lookback_days, threshold_points, tp_sl_ranges, parameter_ranges')),
                ('current_parameters', models.JSONField(blank=True, default=dict, help_text='Current optimized parameters for the bot strategy')),
                ('backtest_range_days', models.PositiveIntegerField(default=90, help_text='Number of days to backtest')),
                ('last_backtest_date', models.DateTimeField(blank=True, help_text='Last time backtest was run', null=True)),
                ('last_optimization_date', models.DateTimeField(blank=True, help_text='Last time optimization was run', null=True)),
                ('allowed_packages', models.ManyToManyField(blank=True, help_text='Subscription packages that can use this bot', related_name='bot_strategies', to='trading.subscriptionpackage')),
            ],
            options={
                'verbose_name': 'Bot Strategy',
                'verbose_name_plural': 'Bot Strategies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usertradeaccount',
            name='active_bot',
            field=models.ForeignKey(blank=True, help_text='Currently assigned bot strategy', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_accounts', to='trading.botstrategy'),
        ),
        migrations.CreateModel(
            name='BacktestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('run_date', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When this backtest was run')),
                ('backtest_start_date', models.DateField(help_text='Start date of backtest period')),
                ('backtest_end_date', models.DateField(help_text='End date of backtest period')),
                ('total_trades', models.PositiveIntegerField(default=0, help_text='Total number of trades')),
                ('winning_trades', models.PositiveIntegerField(default=0, help_text='Number of winning trades')),
                ('losing_trades', models.PositiveIntegerField(default=0, help_text='Number of losing trades')),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Win rate percentage', max_digits=5)),
                ('total_profit', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Total profit/loss', max_digits=19)),
                ('avg_profit_per_trade', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Average profit per trade', max_digits=19)),
                ('best_trade', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Best single trade profit', max_digits=19)),
                ('worst_trade', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Worst single trade loss', max_digits=19)),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Maximum drawdown amount', max_digits=19)),
                ('max_drawdown_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum drawdown percentage', max_digits=5)),
                ('equity_curve_image', models.ImageField(blank=True, help_text='Equity curve chart image', null=True, upload_to='backtest_curves/%Y/%m/')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Additional backtest data (trade list, daily returns, etc.)')),
                ('is_latest', models.BooleanField(db_index=True, default=False, help_text='Whether this is the most recent backtest result for the strategy')),
                ('bot_strategy', models.ForeignKey(help_text='Bot strategy this backtest is for', on_delete=django.db.models.deletion.CASCADE, related_name='backtest_results', to='trading.botstrategy')),
            ],
            options={
                'verbose_name': 'Backtest Result',
                'verbose_name_plural': 'Backtest Results',
                'ordering': ['-run_date'],
                'indexes': [models.Index(fields=['bot_strategy', '-run_date'], name='trading_bac_bot_str_1dee70_idx'), models.Index(fields=['is_latest', '-run_date'], name='trading_bac_is_late_c71c3e_idx')],
            },
        ),
    ]
