# Generated by Django 4.2.26 on 2025-12-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_usertradeaccount_bot_activated_at_botstrategy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradeaccount',
            name='mt5_password',
            field=models.CharField(blank=True, help_text='MT5 Account Password (encrypted)', max_length=200),
        ),
    ]
