# Generated by Django 4.2.26 on 2025-12-14 12:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_usertradeaccount_mt5_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='max_lot_size',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.01'), help_text='Maximum lot size allowed (null = unlimited)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='max_symbols',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of trading symbol pairs allowed (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='min_lot_size',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.01'), help_text='Minimum lot size allowed', max_digits=10),
        ),
    ]
