# Generated by Django 4.2.26 on 2025-12-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_subscriptionpackage_max_lot_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='allow_news_filter',
            field=models.BooleanField(default=False, help_text='Allow automatic bot pause during high-impact news events'),
        ),
    ]
