# Generated by Django 4.2.26 on 2025-12-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_add_news_filter_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='allow_dd_protection',
            field=models.BooleanField(default=False, help_text='Allow drawdown protection configuration'),
        ),
    ]
