# Generated by Django 4.2.26 on 2025-12-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_add_dd_protection_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='backtestresult',
            name='comprehensive_analysis_image',
            field=models.ImageField(blank=True, help_text='Comprehensive analysis chart (Monte Carlo, Walk Forward)', null=True, upload_to='backtest_analysis/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='backtestresult',
            name='trading_graph_image',
            field=models.ImageField(blank=True, help_text='Backtest trading graph showing entry/exit points', null=True, upload_to='backtest_trades/%Y/%m/'),
        ),
    ]
