# Generated by Django 4.2.26 on 2025-12-21 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0014_add_bot_strategy_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradetransaction',
            name='bot_strategy',
            field=models.ForeignKey(blank=True, help_text='Bot that created this trade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='trading.botstrategy'),
        ),
    ]
