# Generated by Django 4.2.26 on 2025-12-24 03:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_add_bot_to_trade'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradeaccount',
            name='peak_balance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Peak account balance', max_digits=19),
        ),
    ]
