# Generated by Django 4.2.26 on 2025-12-24 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_usertradeaccount_peak_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradeaccount',
            name='dd_block_reason',
            field=models.CharField(blank=True, choices=[('DAILY_DD_LIMIT', 'Daily DD Limit Reached'), ('MAX_ACCOUNT_DD', 'Max Account DD Reached')], help_text='Reason for DD block', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usertradeaccount',
            name='dd_blocked',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether bot is blocked due to drawdown protection'),
        ),
        migrations.AddField(
            model_name='usertradeaccount',
            name='dd_blocked_at',
            field=models.DateTimeField(blank=True, help_text='When the bot was blocked by DD protection', null=True),
        ),
    ]
