# Generated by Django 4.2.26 on 2025-12-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_usertradeaccount_dd_block_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradetransaction',
            name='comment',
            field=models.CharField(blank=True, help_text="Comment field from MT5 trade (e.g., '5_MeanReversion_EURUSD')", max_length=255, null=True),
        ),
    ]
