# Generated by Django 4.2.26 on 2026-01-16 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0018_tradetransaction_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpackage',
            name='max_accounts',
            field=models.PositiveIntegerField(default=1, help_text='Maximum number of trading accounts allowed per package (0 = unlimited)'),
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='mt5_reset_allowed_per_period',
            field=models.PositiveIntegerField(default=1, help_text='Number of MT5 account resets allowed per subscription period'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='new_mt5_data',
            field=models.JSONField(blank=True, help_text='New MT5 account details for reset requests (account_name, mt5_account_id, mt5_password, mt5_server, broker_name)', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='request_type',
            field=models.CharField(choices=[('PURCHASE', 'New Purchase'), ('RENEWAL', 'Renewal'), ('MT5_RESET', 'MT5 Account Reset')], default='PURCHASE', help_text='Type of request: new purchase, renewal, or MT5 reset', max_length=20),
        ),
        migrations.AddField(
            model_name='usertradeaccount',
            name='current_period_reset_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of MT5 resets in current subscription period'),
        ),
        migrations.AddField(
            model_name='usertradeaccount',
            name='last_mt5_reset_at',
            field=models.DateTimeField(blank=True, help_text='Last time MT5 account details were reset', null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='trade_account',
            field=models.ForeignKey(blank=True, help_text='Trade account (null for initial purchase before MT5 setup)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='trading.usertradeaccount'),
        ),
        migrations.CreateModel(
            name='UserPackageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('quota_total', models.PositiveIntegerField(help_text='Total number of accounts allowed by this quota')),
                ('accounts_used', models.PositiveIntegerField(default=0, help_text='Number of accounts currently using this quota')),
                ('start_date', models.DateTimeField(help_text='When this quota becomes active')),
                ('expiry_date', models.DateTimeField(db_index=True, help_text='When this quota expires')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], db_index=True, default='ACTIVE', max_length=20)),
                ('subscription_package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_quotas', to='trading.subscriptionpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_quotas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Package Quota',
                'verbose_name_plural': 'User Package Quotas',
                'ordering': ['-expiry_date'],
                'indexes': [models.Index(fields=['user', 'status', '-expiry_date'], name='trading_use_user_id_6af818_idx')],
            },
        ),
    ]
