# Generated by Django 4.2.26 on 2026-01-19 10:27

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0019_subscriptionpackage_max_accounts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('code', models.CharField(db_index=True, help_text='Unique referral code for the user', max_length=20, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Promotional discount percentage for referred friends (e.g., 10.00 for 10%)', max_digits=5)),
                ('description', models.CharField(blank=True, help_text='Marketing description or campaign name for this referral code', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Code',
                'verbose_name_plural': 'Referral Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('package_price', models.DecimalField(decimal_places=2, help_text='Original package price at time of purchase', max_digits=10)),
                ('referral_percentage', models.DecimalField(decimal_places=2, help_text='Percentage rate applied', max_digits=5)),
                ('credit_earned', models.DecimalField(decimal_places=2, help_text='Credit amount earned by referrer', max_digits=10)),
                ('is_recurring', models.BooleanField(default=False, help_text='Whether this is a recurring monthly credit')),
                ('month_number', models.PositiveIntegerField(default=1, help_text='Which month this earning is for (1=first month, 2=second, etc.)')),
                ('referee', models.ForeignKey(help_text='User who was referred', on_delete=django.db.models.deletion.CASCADE, related_name='referred_by_earnings', to=settings.AUTH_USER_MODEL)),
                ('referral_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='earnings', to='trading.referralcode')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Earning',
                'verbose_name_plural': 'Referral Earnings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscriptionpackage',
            name='referral_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage of package price as credit for referrer (e.g., 20.00 for 20%)', max_digits=5),
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Available credit balance in THB', max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Credit',
                'verbose_name_plural': 'User Credits',
            },
        ),
        migrations.CreateModel(
            name='ReferralTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'Credit Added'), ('DEBIT', 'Credit Used')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('referral_earning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='trading.referralearnings')),
                ('subscription_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='trading.subscriptionpayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Transaction',
                'verbose_name_plural': 'Referral Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='referralearnings',
            name='subscription_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referral_earnings', to='trading.subscriptionpackage'),
        ),
        migrations.AddField(
            model_name='referralearnings',
            name='subscription_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_earnings', to='trading.subscriptionpayment'),
        ),
        migrations.AlterUniqueTogether(
            name='referralearnings',
            unique_together={('referrer', 'referee', 'subscription_payment')},
        ),
    ]
