# Generated by Django 4.2.26 on 2026-01-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_referralcode_referralearnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='referral_code',
            field=models.ForeignKey(blank=True, help_text='Referral code used in this purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_payments', to='trading.referralcode'),
        ),
    ]
