# Generated by Django 4.2.26 on 2026-01-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0021_subscriptionpayment_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertradeaccount',
            name='account_type',
            field=models.CharField(choices=[('PRO', 'Pro (No Suffix)'), ('STANDARD', 'Standard'), ('CENT', 'Cent')], default='PRO', help_text='Account type determines symbol suffix pattern', max_length=20),
        ),
        migrations.AddField(
            model_name='usertradeaccount',
            name='symbol_suffix',
            field=models.CharField(blank=True, default='', help_text="Symbol suffix (e.g., 'm' for Standard, 'c' for Cent, empty for Pro)", max_length=10),
        ),
    ]
